"""init_db_with_superadmin

Revision ID: 2f9addfc4d4a
Revises: b45003ff16eb
Create Date: 2026-05-24 19:25:30.390744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f9addfc4d4a'
down_revision: Union[str, Sequence[str], None] = 'b45003ff16eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('passport_series', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'passport_series')
    # ### end Alembic commands ###
